#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <source_file>"
    exit 1
fi

# Extract filename without extension
filename=$(basename -- "$1")
filename="${filename%.*}"

# Compile C program
cc -o "$filename" "$1" 2> comp.log

# Check if compilation was successful
if [ $? -eq 0 ]; then
    # Compilation successful, execute the program
    "./$filename"
else
    # Compilation failed, display error log
    less comp.log
fi

